### ISSUE TITLE
Add version in the file name

### ISSUE THREAD

**Issue by RaeesBhatti** [steelbrain/JS-Mods#6]
It will solve caching problems and stuff.

**Comment by steelbrain** [comment]
What version do you mean?

**Comment by RaeesBhatti** [comment]
the "version" of the JS-Mods

**Comment by steelbrain** [comment]
That is a caching limitation, solving it in this project won't be ideal if we can solve it globally. WordPress and other CMS/Apps workaround this caching limitation by specifying a version in the query string like `jquery.js?v=2.0.0`. I would suggest you try that.
